apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0Kcm91dGU6CiAgZ3JvdXBfYnk6IFsnam9iJ10KICBncm91cF93YWl0OiAzMHMKICBncm91cF9pbnRlcnZhbDogNW0KICByZXBlYXRfaW50ZXJ2YWw6IDEyaAogIHJlY2VpdmVyOiAnc2xhY2tfaWNjX21vbml0b3JpbmcnCgpyZWNlaXZlcnM6CgotIG5hbWU6ICd3ZWJob29rJwogIHdlYmhvb2tfY29uZmlnczoKICAtIHVybDogJ2h0dHA6Ly9hbGVydG1hbmFnZXJ3aDozMDUwMC8nCgotIG5hbWU6IHNsYWNrX2ljY19tb25pdG9yaW5nCiAgc2xhY2tfY29uZmlnczoKICAgIC0gYXBpX3VybDogaHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDVHQ0FIUkUxL0I1TUgxVEJTNy9kdVBNVEs2blk1dHFZbGN0ZmRjdlVkQjUKICAgICAgY2hhbm5lbDogJyNpY2MtbW9uaXRvcmluZycK
