apiVersion: v1
kind: Service
metadata:
  name: etcd-k8s
  labels:
    k8s-app: etcd
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: api
    port: 2379
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: etcd-k8s
  labels:
    k8s-app: etcd
subsets:
- addresses:
  - ip: 141.22.30.32
    nodeName: icc-etcd-1.informatik.haw-hamburg.de
  - ip: 141.22.30.33
    nodeName: icc-etcd-2.informatik.haw-hamburg.de
  - ip: 141.22.30.34
    nodeName: icc-etcd-3.informatik.haw-hamburg.de
  - ip: 141.22.30.35
    nodeName: icc-etcd-4.informatik.haw-hamburg.de
  - ip: 141.22.30.36
    nodeName: icc-etcd-5.informatik.haw-hamburg.de
  ports:
  - name: api
    port: 2379
    protocol: TCP
