apiVersion: v1
kind: Service
metadata:
  name: kube-scheduler-prometheus-discovery
  labels:
    k8s-app: kube-scheduler
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10251
    targetPort: 10251
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kube-scheduler-prometheus-discovery
  labels:
    k8s-app: kube-scheduler
subsets:
- addresses:
  - ip: 141.22.10.223
  - ip: 141.22.10.224
  - ip: 141.22.10.225
  ports:
  - name: http-metrics
    port: 10251
    protocol: TCP
