apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: rbd2
spec:
  containers:
  - image: kubernetes/pause
    imagePullPolicy: Always
    name: rbd-rw
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt/rbd
      name: rbdpd
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  terminationGracePeriodSeconds: 30
  volumes:
  - name: rbdpd
    rbd:
      fsType: ext4
      image: foo
      keyring: /etc/ceph/keyring
      monitors:
      - ceph-osd1.ful.informatik.haw-hamburg.de:6789
      - ceph-osd2.ful.informatik.haw-hamburg.de:6789
      - ceph-osd3.ful.informatik.haw-hamburg.de:6789
      pool: rbd
      readOnly: true
      secretRef:
        name: ceph-secret
      user: admin
status: {}
